package runtime

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/chentianyu/celestia/internal/models"
	"github.com/google/uuid"
)

type WritingTopicRequest struct {
	ID    string `json:"id,omitempty"`
	Title string `json:"title"`
}

type WritingMaterialRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type WritingStateUpdateRequest struct {
	Section string `json:"section"`
	Content string `json:"content"`
}

func (s *Service) SaveWritingTopic(ctx context.Context, req WritingTopicRequest) (models.AgentWritingTopic, error) {
	if err := requireText(req.Title, "title"); err != nil {
		return models.AgentWritingTopic{}, err
	}
	now := time.Now().UTC()
	var saved models.AgentWritingTopic
	_, err := s.update(ctx, func(snapshot *models.AgentSnapshot) error {
		targetID := firstNonEmpty(req.ID, uuid.NewString())
		for idx := range snapshot.Writing.Topics {
			if snapshot.Writing.Topics[idx].ID == targetID {
				snapshot.Writing.Topics[idx].Title = strings.TrimSpace(req.Title)
				snapshot.Writing.Topics[idx].UpdatedAt = now
				var prepErr error
				saved, prepErr = prepareWritingTopic(snapshot.Writing.Topics[idx])
				if prepErr != nil {
					return prepErr
				}
				snapshot.Writing.Topics[idx] = saved
				return nil
			}
		}
		saved = models.AgentWritingTopic{
			ID:        targetID,
			Title:     strings.TrimSpace(req.Title),
			Status:    "active",
			Materials: []models.AgentWritingMaterial{},
			CreatedAt: now,
			UpdatedAt: now,
		}
		var prepErr error
		saved, prepErr = prepareWritingTopic(saved)
		if prepErr != nil {
			return prepErr
		}
		snapshot.Writing.Topics = append([]models.AgentWritingTopic{saved}, snapshot.Writing.Topics...)
		snapshot.Writing.UpdatedAt = now
		snapshot.UpdatedAt = now
		return nil
	})
	return saved, err
}

func (s *Service) AddWritingMaterial(ctx context.Context, topicID string, req WritingMaterialRequest) (models.AgentWritingTopic, error) {
	if err := requireText(topicID, "topic_id"); err != nil {
		return models.AgentWritingTopic{}, err
	}
	if err := requireText(req.Content, "content"); err != nil {
		return models.AgentWritingTopic{}, err
	}
	now := time.Now().UTC()
	var saved models.AgentWritingTopic
	_, err := s.update(ctx, func(snapshot *models.AgentSnapshot) error {
		topic, ok := findWritingTopic(snapshot.Writing.Topics, topicID)
		if !ok {
			return errors.New("writing topic not found")
		}
		material := models.AgentWritingMaterial{
			ID:        uuid.NewString(),
			Title:     strings.TrimSpace(firstNonEmpty(req.Title, "Material")),
			Content:   strings.TrimSpace(req.Content),
			CreatedAt: now,
		}
		persisted, nextTopic, persistErr := persistWritingMaterial(topic, material)
		if persistErr != nil {
			return persistErr
		}
		topic = nextTopic
		topic.Materials = append([]models.AgentWritingMaterial{persisted}, topic.Materials...)
		topic.UpdatedAt = now
		topic, persistErr = prepareWritingTopic(topic)
		if persistErr != nil {
			return persistErr
		}
		saved = topic
		replaceWritingTopic(snapshot, topic)
		return nil
	})
	return saved, err
}

func (s *Service) SummarizeWritingTopic(ctx context.Context, topicID string) (models.AgentWritingTopic, error) {
	var topic models.AgentWritingTopic
	snapshot, err := s.Snapshot(ctx)
	if err != nil {
		return models.AgentWritingTopic{}, err
	}
	var ok bool
	topic, ok = findWritingTopic(snapshot.Writing.Topics, topicID)
	if !ok {
		return models.AgentWritingTopic{}, errors.New("writing topic not found")
	}
	if len(topic.Materials) == 0 {
		return models.AgentWritingTopic{}, errors.New("writing topic has no materials")
	}
	state := fallbackWritingState(topic)
	if generated, genErr := s.GenerateText(ctx, buildWritingPrompt(topic)); genErr == nil {
		state.Summary = generated
		state.Outline = "Generated by configured LLM provider."
		state.Draft = generated
	}
	now := time.Now().UTC()
	var saved models.AgentWritingTopic
	_, err = s.update(ctx, func(snapshot *models.AgentSnapshot) error {
		current, ok := findWritingTopic(snapshot.Writing.Topics, topicID)
		if !ok {
			return errors.New("writing topic not found")
		}
		current.Backup = current.State
		current.State = state
		current.UpdatedAt = now
		var persistErr error
		current, persistErr = persistWritingState(current, current.Backup, state, now)
		if persistErr != nil {
			return persistErr
		}
		saved = current
		replaceWritingTopic(snapshot, current)
		return nil
	})
	return saved, err
}

func (s *Service) RestoreWritingTopic(ctx context.Context, topicID string) (models.AgentWritingTopic, error) {
	if err := requireText(topicID, "topic_id"); err != nil {
		return models.AgentWritingTopic{}, err
	}
	now := time.Now().UTC()
	var saved models.AgentWritingTopic
	_, err := s.update(ctx, func(snapshot *models.AgentSnapshot) error {
		current, ok := findWritingTopic(snapshot.Writing.Topics, topicID)
		if !ok {
			return errors.New("writing topic not found")
		}
		current.State, current.Backup = current.Backup, current.State
		current.UpdatedAt = now
		var persistErr error
		current, persistErr = persistWritingState(current, current.Backup, current.State, now)
		if persistErr != nil {
			return persistErr
		}
		saved = current
		replaceWritingTopic(snapshot, current)
		return nil
	})
	return saved, err
}

func (s *Service) SetWritingTopicState(ctx context.Context, topicID string, req WritingStateUpdateRequest) (models.AgentWritingTopic, error) {
	if err := requireText(topicID, "topic_id"); err != nil {
		return models.AgentWritingTopic{}, err
	}
	section := strings.ToLower(strings.TrimSpace(req.Section))
	if section != "summary" && section != "outline" && section != "draft" {
		return models.AgentWritingTopic{}, errors.New("section must be summary, outline, or draft")
	}
	if err := requireText(req.Content, "content"); err != nil {
		return models.AgentWritingTopic{}, err
	}
	now := time.Now().UTC()
	var saved models.AgentWritingTopic
	_, err := s.update(ctx, func(snapshot *models.AgentSnapshot) error {
		current, ok := findWritingTopic(snapshot.Writing.Topics, topicID)
		if !ok {
			return errors.New("writing topic not found")
		}
		current.Backup = current.State
		switch section {
		case "summary":
			current.State.Summary = strings.TrimSpace(req.Content)
		case "outline":
			current.State.Outline = strings.TrimSpace(req.Content)
		case "draft":
			current.State.Draft = strings.TrimSpace(req.Content)
		}
		current.UpdatedAt = now
		var persistErr error
		current, persistErr = persistWritingState(current, current.Backup, current.State, now)
		if persistErr != nil {
			return persistErr
		}
		saved = current
		replaceWritingTopic(snapshot, current)
		return nil
	})
	return saved, err
}

func findWritingTopic(topics []models.AgentWritingTopic, id string) (models.AgentWritingTopic, bool) {
	for _, topic := range topics {
		if topic.ID == id {
			return topic, true
		}
	}
	return models.AgentWritingTopic{}, false
}

func replaceWritingTopic(snapshot *models.AgentSnapshot, topic models.AgentWritingTopic) {
	for idx := range snapshot.Writing.Topics {
		if snapshot.Writing.Topics[idx].ID == topic.ID {
			snapshot.Writing.Topics[idx] = topic
			snapshot.Writing.UpdatedAt = topic.UpdatedAt
			snapshot.UpdatedAt = topic.UpdatedAt
			return
		}
	}
}

func fallbackWritingState(topic models.AgentWritingTopic) models.AgentWritingState {
	var outline strings.Builder
	var draft strings.Builder
	outline.WriteString("# ")
	outline.WriteString(topic.Title)
	outline.WriteString("\n")
	for _, material := range topic.Materials {
		outline.WriteString("- ")
		outline.WriteString(firstNonEmpty(material.Title, "Material"))
		outline.WriteString("\n")
		draft.WriteString("## ")
		draft.WriteString(firstNonEmpty(material.Title, "Material"))
		draft.WriteString("\n\n")
		draft.WriteString(material.Content)
		draft.WriteString("\n\n")
	}
	return models.AgentWritingState{
		Summary: "Collected " + intString(len(topic.Materials)) + " materials for " + topic.Title + ".",
		Outline: strings.TrimSpace(outline.String()),
		Draft:   strings.TrimSpace(draft.String()),
	}
}

func buildWritingPrompt(topic models.AgentWritingTopic) string {
	var b strings.Builder
	b.WriteString("Organize the following materials into summary, outline, and draft notes for topic: ")
	b.WriteString(topic.Title)
	b.WriteString("\n")
	for _, material := range topic.Materials {
		b.WriteString("\n## ")
		b.WriteString(firstNonEmpty(material.Title, "Material"))
		b.WriteString("\n")
		b.WriteString(material.Content)
	}
	return b.String()
}
